# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-14 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20170514_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=5)),
                ('username', models.CharField(max_length=20)),
            ],
        ),
    ]
