# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-14 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='group_id',
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
    ]
